### ISSUE TITLE
usernames dont always work

### ISSUE THREAD

**Issue by NotTravis** [NihadBadalov/RobloxAccountGeneratorSelenium#6]
sometimes it will say username not approperiate and the program crashes and id have to re run it. so if yuo can like make it so its actual words or use ai or something bro idk random letters and numbers dont always work they think its credit card or something

**Comment by NihadBadalov** [comment]
ok

**Comment by NihadBadalov** [comment]
Changed in a11c8a6. Tell me what you think

**Comment by NotTravis** [comment]
line 202, in <module>
    with open("alts.txt", "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'alts.txt'

**Comment by NihadBadalov** [comment]
Oh I see. Create an "alts.txt" file in the directory with the `main.py` file. I'll push an update where a file will be created if it doesn't exist. Thank you. Anything else?
