### ISSUE TITLE
I cant start the program

### ISSUE THREAD

**Issue by Mario03482** [NihadBadalov/RobloxAccountGeneratorSelenium#7]
Hi, as the title says I can't start the program because I am a noob totally, can you pls help me?

**Comment by NihadBadalov** [comment]
Hi!

Watch a tutorial on YouTube how to install Python (if not installing from the official website, make sure the version is 3.8+)

Then follow the Requirements part of the README

If you have any questions, don't hesitate to ask!

**Comment by NihadBadalov** [comment]
@Mario03482 If you need any help, feel free to write here.

I will close this Issue in a day or two in case of inactivity.

**Feel free to open a new Issue if you have questions or need help!**
